index:
  path: /
  controller: App\Controller\TestController::yay

article:
  path: /article/{page}
  controller: App\Controller\TestController::yoy
  defaults:
    page: 14
  requirements:
    page: '\d+'

new:
  path: /new
  controller: App\Controller\TestController::yuy

process:
  path: /test
  controller: App\Controller\TestController::process