index:
  path: /
  controller: App\Controller\MainController::Main

article:
  path: /article/{page}
  controller: App\Controller\MainController::Article
  defaults:
    page: 14
  requirements:
    page: '\d+'

new:
  path: /new
  controller: App\Controller\MainController::Redaction

process:
  path: /proc
  controller: App\Controller\MainController::Process